In [ ]:
import pandas as pd
import os
import numpy as np
import shutil
import requests

In [ ]:
df = pd.read_csv(r"D:\AI\projects\deep fake detection\data\FINAL_DATASET.csv")
df.head()

In [ ]:
df.info()

In [ ]:
df['detection_difficulty'].unique()

In [ ]:
df['gender'].value_counts()

In [ ]:
os.makedirs('images' , exist_ok=True)

In [ ]:
df['image_url'].isna().sum()

In [ ]:
# valid_rows = []

# skipped = 0

# for index , rows in df.iterrows():

#     try:

#         url = df['image_url'].iloc[index]
#         label = df['label_numeric'].iloc[index]
#         dataset_split = df['dataset_split'].iloc[index]

#         print(url)

#         image = requests.get(url, timeout=10)

#         if image.status_code != 200:
#             skipped += 1
#             continue

#         filename = f"{index}.jpg"

#         with open(f"images/{filename}", "wb") as f:
#             f.write(image.content)

#         valid_rows.append({
#             "image_name": filename,
#             "label": label,
#             "dataset_split": dataset_split
#         })

#     except requests.exceptions.ConnectionError:
#         print(f"Connection Error at: {url}")
#         skipped += 1
#         continue

#     except requests.exceptions.Timeout:
#         print(f"Timeout at: {url}")
#         skipped += 1
#         continue

#     except Exception as e:
#         print(f"Error at {url}: {e}")
#         skipped += 1
#         continue

In [ ]:
# image_data = pd.DataFrame(columns = ['image' , 'label'])

# for i , data  in enumerate(valid_rows):
#     image_data.loc[i , 'image'] = valid_rows[i]['image_name']
#     image_data.loc[i , 'label'] = valid_rows[i]['label']
#     image_data.loc[i , 'dataset_split'] = valid_rows[i]['dataset_split']



# image_data.to_csv('image_label.csv')

In [ ]:
image_data = pd.read_csv('image_label.csv' , index_col=0 )
image_data

         image  label dataset_split
0        0.jpg      1         train
1        1.jpg      1         train
2        2.jpg      1          test
3        3.jpg      1         train
4        4.jpg      1         train
...        ...    ...           ...
5351  5552.jpg      0         train
5352  5553.jpg      0         train
5353  5554.jpg      0         train
5354  5555.jpg      0         train
5355  5556.jpg      0         train

[5356 rows x 3 columns]

In [ ]:
image_data['image'] =  r"D:\AI\projects\deep fake detection\data\images\\" + image_data['image']

In [ ]:
image_data

                                                  image  label dataset_split
0     D:\AI\projects\deep fake detection\data\images...      1         train
1     D:\AI\projects\deep fake detection\data\images...      1         train
2     D:\AI\projects\deep fake detection\data\images...      1          test
3     D:\AI\projects\deep fake detection\data\images...      1         train
4     D:\AI\projects\deep fake detection\data\images...      1         train
...                                                 ...    ...           ...
5351  D:\AI\projects\deep fake detection\data\images...      0         train
5352  D:\AI\projects\deep fake detection\data\images...      0         train
5353  D:\AI\projects\deep fake detection\data\images...      0         train
5354  D:\AI\projects\deep fake detection\data\images...      0         train
5355  D:\AI\projects\deep fake detection\data\images...      0         train

[5356 rows x 3 columns]

In [ ]:
destination_folder_train_AI = r"D:\AI\projects\deep fake detection\data\train\AI"
destination_folder_train_real = r"D:\AI\projects\deep fake detection\data\train\REAL"
destination_folder_test_AI = r"D:\AI\projects\deep fake detection\data\test\AI"
destination_folder_test_real = r"D:\AI\projects\deep fake detection\data\test\REAL"
destination_folder_val_AI = r"D:\AI\projects\deep fake detection\data\val\AI"
destination_folder_val_real = r"D:\AI\projects\deep fake detection\data\val\REAL"


for  i , image_path in enumerate(image_data["image"]):

    if image_data.loc[i ,'dataset_split'] == 'train':
        if image_data.loc[i ,'label'] == 1:
            shutil.copy(image_path, destination_folder_train_real)
        elif image_data.loc[i ,'label'] == 0:
            shutil.copy(image_path, destination_folder_train_AI)

    elif image_data.loc[i ,'dataset_split'] == 'test':
        if image_data.loc[i ,'label'] == 1:
            shutil.copy(image_path, destination_folder_test_real)
        elif image_data.loc[i ,'label'] == 0:
            shutil.copy(image_path, destination_folder_test_AI)

    elif image_data.loc[i ,'dataset_split'] == 'val':
        if image_data.loc[i ,'label'] == 1:
            shutil.copy(image_path, destination_folder_val_real)
        elif image_data.loc[i ,'label'] == 0:
            shutil.copy(image_path, destination_folder_val_AI)